local color_utils = require("colorly.utils.colors")

return function(C)
  return {
    NeogitBranch = { fg = C.Mu },
    NeogitRemote = { fg = C.Green },
    NeogitUnmergedInto = { link = "Function" },
    NeogitUnpulledFrom = { link = "Function" },
    NeogitObjectId = { link = "Comment" },
    NeogitStash = { link = "Comment" },
    NeogitRebaseDone = { link = "Comment" },
    NeogitHunkHeader = {
      bg = color_utils.darken(C.Info, 0.095, C.Bg1),
      fg = color_utils.darken(C.Info, 0.5, C.Bg1),
    },
    NeogitHunkHeaderHighlight = {
      bg = color_utils.darken(C.Info, 0.215, C.Bg1),
      fg = C.Info,
    },
    NeogitDiffContextHighlight = { bg = C.Bg3 },
    NeogitDiffDeleteHighlight = {
      bg = color_utils.darken(C.VcsDeleted, 0.345, C.Bg1),
      fg = color_utils.lighten(C.VcsDeleted, 0.850, C.Text),
    },
    NeogitDiffAddHighlight = {
      bg = color_utils.darken(C.VcsAdded, 0.345, C.Bg1),
      fg = color_utils.lighten(C.VcsAdded, 0.850, C.Text),
    },
    NeogitDiffDelete = {
      bg = color_utils.darken(C.VcsDeleted, 0.095, C.Bg1),
      fg = color_utils.darken(C.VcsDeleted, 0.800, C.Bg1),
    },
    NeogitDiffAdd = {
      bg = color_utils.darken(C.VcsAdded, 0.095, C.Bg1),
      fg = color_utils.darken(C.VcsAdded, 0.800, C.Bg1),
    },
    NeogitCommitViewHeader = {
      bg = color_utils.darken(C.Info, 0.300, C.Bg1),
      fg = color_utils.lighten(C.Info, 0.800, C.Text),
    },
    NeogitChangeModified = { fg = C.VcsModified },
    NeogitChangeDeleted = { fg = C.VcsDeleted },
    NeogitChangeAdded = { fg = C.VcsAdded },
    NeogitChangeRenamed = { fg = C.VcsRenamed },
    NeogitChangeUpdated = { fg = C.VcsModified },
    NeogitChangeCopied = { fg = C.VcsRenamed },
    NeogitChangeBothModified = { fg = C.VcsModified },
    NeogitChangeNewFile = { fg = C.VcsAdded },
    NeogitUntrackedfiles = { fg = C.VcsUntracked },
    NeogitUnstagedchanges = { fg = C.VcsOther },
    NeogitUnmergedchanges = { fg = C.VcsOther },
    NeogitUnpulledchanges = { fg = C.VcsOther },
    NeogitRecentcommits = { fg = C.VcsOther },
    NeogitStagedchanges = { fg = C.VcsOther },
    NeogitStashes = { fg = C.VcsOther },
    NeogitRebasing = { fg = C.VcsOther },
    NeogitNotificationInfo = { fg = C.Info },
    NeogitNotificationWarning = { fg = C.Warning },
    NeogitNotificationError = { fg = C.Error },
    NeogitGraphRed = { fg = C.Red },
    NeogitGraphWhite = { fg = C.White },
    NeogitGraphYellow = { fg = C.Yellow },
    NeogitGraphGreen = { fg = C.Green },
    NeogitGraphCyan = { fg = C.Cyan },
    NeogitGraphBlue = { fg = C.Blue },
    NeogitGraphPurple = { fg = C.Magenta },
    NeogitGraphGray = { fg = C.TextDim1 },
    NeogitGraphOrange = { fg = C.Orange },
    NeogitGraphBoldRed = { fg = C.Red, bold = true },
    NeogitGraphBoldWhite = { fg = C.White, bold = true },
    NeogitGraphBoldYellow = { fg = C.Yellow, bold = true },
    NeogitGraphBoldGreen = { fg = C.green, bold = true },
    NeogitGraphBoldCyan = { fg = C.Cyan, bold = true },
    NeogitGraphBoldBlue = { fg = C.Blue, bold = true },
    NeogitGraphBoldPurple = { fg = C.Magenta, bold = true },
    NeogitGraphBoldGray = { fg = C.TextDim1, bold = true },
    NeogitDiffContext = { bg = C.Bg1 },
    NeogitPopupBold = { bold = true },
    NeogitPopupSwitchKey = { fg = C.Cyan },
    NeogitPopupOptionKey = { fg = C.Cyan },
    NeogitPopupConfigKey = { fg = C.Cyan },
    NeogitPopupActionKey = { fg = C.Cyan },
    NeogitFilePath = { fg = C.Files },
    NeogitDiffHeader = { bg = C.Bg1, fg = C.Info },
    NeogitDiffHeaderHighlight = { bg = C.Bg1, fg = C.VcsModified },
    NeogitUnpushedTo = { fg = C.Info },
    NeogitFold = { fg = C.none, bg = C.none },
    NeogitSectionHeader = { fg = C.Accent2 },
    NeogitTagName = { link = "Type" },
    NeogitTagDistance = { fg = C.Info },
    NeogitWinSeparator = { link = "WinSeparator" },
  }
end
